version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      # init and analyze reject a config written by another CodeQL version, so
      # their bumps must arrive in one PR.
      codeql-action:
        patterns:
          - "github/codeql-action*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
