"""Provider-neutral AI code review primitives for ReviewSensei."""

from .concurrency import ConcurrencyGroup, ReviewConcurrencyPlan
from .context import (
    ContextSnapshot,
    FindingLifecycle,
    RepositoryContextStore,
    ReviewContextCache,
    ReviewContextCacheKey,
    ReviewContextSelection,
    SourceContextExcerpt,
    SourceContextSelection,
    SymbolAwareContextSelector,
    build_review_context_selection,
    reconcile_finding_lifecycle,
    stable_concern_identity,
    stable_finding_fingerprint,
)
from .conversation import ConversationService
from .evaluation import PromotionRecord, validate_promotion_record
from .learnings import (
    LearningDiagnostic,
    LearningFeedback,
    LearningStore,
    load_repository_learnings,
)
from .models import (
    ConversationContext,
    ConversationFinding,
    ConversationMessage,
    ConversationReply,
    LearningEntry,
    LearningProposal,
    ProviderRequest,
    ProviderResponse,
    ReviewComment,
    ReviewDocument,
    ReviewLensContext,
    ReviewRequest,
    ReviewResult,
)
from .outcomes import RecoveryArtifact, ResourceBudget, RunOutcome
from .release_manifest import (
    Artifact,
    CompatibilityManifest,
    validate_compatibility_manifest,
)
from .service import ReviewService
from .stages import (
    ContextDocumentSource,
    ReviewCategory,
    ReviewCategoryCatalog,
    Stage,
    load_review_categories_from_dir,
    load_stages_from_dir,
)
from .validation import DEFAULT_REVIEW_LIMITS, ReviewLimits
from .verifier import (
    CandidateFinding,
    EvidenceReference,
    VerificationResult,
    verify_candidate,
    verify_candidates,
)

__all__ = [
    "ConcurrencyGroup",
    "ContextDocumentSource",
    "ConversationContext",
    "ConversationFinding",
    "ConversationMessage",
    "ConversationReply",
    "ConversationService",
    "ContextSnapshot",
    "FindingLifecycle",
    "PromotionRecord",
    "validate_promotion_record",
    "Artifact",
    "CompatibilityManifest",
    "validate_compatibility_manifest",
    "LearningEntry",
    "LearningProposal",
    "LearningStore",
    "LearningDiagnostic",
    "LearningFeedback",
    "load_repository_learnings",
    "ProviderRequest",
    "ProviderResponse",
    "RepositoryContextStore",
    "SourceContextExcerpt",
    "SourceContextSelection",
    "SymbolAwareContextSelector",
    "ReviewContextCache",
    "ReviewContextCacheKey",
    "ReviewContextSelection",
    "ReviewComment",
    "ReviewDocument",
    "ReviewLensContext",
    "ReviewLimits",
    "ReviewCategory",
    "ReviewCategoryCatalog",
    "ReviewConcurrencyPlan",
    "ReviewRequest",
    "ReviewResult",
    "ReviewService",
    "stable_finding_fingerprint",
    "stable_concern_identity",
    "reconcile_finding_lifecycle",
    "RecoveryArtifact",
    "ResourceBudget",
    "RunOutcome",
    "CandidateFinding",
    "EvidenceReference",
    "VerificationResult",
    "verify_candidate",
    "verify_candidates",
    "DEFAULT_REVIEW_LIMITS",
    "Stage",
    "build_review_context_selection",
    "load_review_categories_from_dir",
    "load_stages_from_dir",
]
