"""Provider-neutral AI code review primitives for ReviewSensei."""

from .concurrency import (
    AdmissionLease,
    AdmissionOutcome,
    ConcurrencyGroup,
    ProviderAdmission,
    ReviewConcurrencyPlan,
)
from .context import (
    ContextSnapshot,
    FindingLifecycle,
    RepositoryContextStore,
    ReviewContextCache,
    ReviewContextCacheKey,
    ReviewContextSelection,
    SourceContextCoverage,
    SourceContextExcerpt,
    SourceContextSelection,
    SymbolAwareContextPolicy,
    SymbolAwareContextSelector,
    build_review_context_selection,
    reconcile_finding_lifecycle,
    stable_concern_identity,
    stable_finding_fingerprint,
)
from .conversation import ConversationService
from .diagnostics import build_plan, run_doctor
from .errors import AdmissionCancelled, AdmissionRejected
from .evaluation import (
    PromotionRecord,
    engine_digest,
    promotion_record_from_reports,
    prompt_digest,
    require_supported_promotion,
    validate_promotion_against_report,
    validate_promotion_record,
)
from .learnings import (
    LearningDiagnostic,
    LearningFeedback,
    LearningStore,
    learning_digest,
    load_learning_feedback,
    load_repository_learnings,
    summarize_learning_feedback,
)
from .models import (
    ConversationContext,
    ConversationFinding,
    ConversationMessage,
    ConversationReply,
    LearningEntry,
    LearningProposal,
    ProviderRequest,
    ProviderResponse,
    ReviewComment,
    ReviewDocument,
    ReviewLensContext,
    ReviewRequest,
    ReviewResult,
)
from .outcomes import RecoveryArtifact, ResourceBudget, RunOutcome
from .patches import PatchSuggestion, create_patch_suggestion
from .release_manifest import (
    Artifact,
    CompatibilityManifest,
    validate_compatibility_manifest,
)
from .service import ReviewService
from .stages import (
    ContextDocumentSource,
    ReviewCategory,
    ReviewCategoryCatalog,
    Stage,
    load_review_categories_from_dir,
    load_stages_from_dir,
)
from .validation import DEFAULT_REVIEW_LIMITS, ReviewLimits
from .verifier import (
    CandidateFinding,
    EvidenceReference,
    VerificationResult,
    verify_candidate,
    verify_candidates,
)
from .workflow import ReviewExecutionPlan, plan_review_execution

__all__ = [
    "AdmissionCancelled",
    "AdmissionLease",
    "AdmissionOutcome",
    "AdmissionRejected",
    "ConcurrencyGroup",
    "ProviderAdmission",
    "ContextDocumentSource",
    "ConversationContext",
    "ConversationFinding",
    "ConversationMessage",
    "ConversationReply",
    "ConversationService",
    "LearningEntry",
    "LearningProposal",
    "LearningStore",
    "LearningDiagnostic",
    "LearningFeedback",
    "load_repository_learnings",
    "load_learning_feedback",
    "summarize_learning_feedback",
    "learning_digest",
    "ProviderRequest",
    "ProviderResponse",
    "RepositoryContextStore",
    "ContextSnapshot",
    "SourceContextCoverage",
    "SourceContextExcerpt",
    "SourceContextSelection",
    "SymbolAwareContextPolicy",
    "SymbolAwareContextSelector",
    "ReviewContextCache",
    "ReviewContextCacheKey",
    "FindingLifecycle",
    "ReviewContextSelection",
    "ReviewComment",
    "ReviewDocument",
    "ReviewLensContext",
    "ReviewLimits",
    "ReviewCategory",
    "ReviewCategoryCatalog",
    "ReviewConcurrencyPlan",
    "ReviewRequest",
    "ReviewResult",
    "ReviewService",
    "stable_finding_fingerprint",
    "stable_concern_identity",
    "reconcile_finding_lifecycle",
    "ReviewExecutionPlan",
    "DEFAULT_REVIEW_LIMITS",
    "Stage",
    "build_review_context_selection",
    "build_plan",
    "run_doctor",
    "PatchSuggestion",
    "create_patch_suggestion",
    "load_review_categories_from_dir",
    "load_stages_from_dir",
    "plan_review_execution",
    "PromotionRecord",
    "engine_digest",
    "prompt_digest",
    "promotion_record_from_reports",
    "require_supported_promotion",
    "validate_promotion_against_report",
    "validate_promotion_record",
    "RecoveryArtifact",
    "ResourceBudget",
    "RunOutcome",
    "Artifact",
    "CompatibilityManifest",
    "validate_compatibility_manifest",
    "CandidateFinding",
    "EvidenceReference",
    "VerificationResult",
    "verify_candidate",
    "verify_candidates",
]
