"""GitHub App identity, installation-time setup, and webhook safety.

This package is a narrow transport/auth boundary outside the provider-neutral
review core. It owns GitHub App JWTs, installation-token exchange, token
caching, webhook signature verification, sanitized webhook failures, and
idempotent installation-time setup pull request bootstrap for optional
App-identity comments, reviews, or setup.
"""

from .application import GitHubApplication, GitHubWriteOptions
from .auth import (
    AppInstallationToken,
    EnvPrivateKeySource,
    FilePrivateKeySource,
    GitHubAppAuth,
    GitHubTokenTransport,
    InstallationToken,
    InstallationTokenScope,
    PrivateKeySource,
    RequestedPermissions,
)
from .broker import (
    DEFAULT_BROKER_AUDIENCE,
    ApprovedWorkflow,
    AuditRecord,
    AuditSink,
    BrokerPolicy,
    ForkChecker,
    GitHubForkChecker,
    GitHubInstallationLookup,
    InMemoryAuditSink,
    InMemoryInstallationMapping,
    InstallationMapping,
    OIDCBroker,
    RateLimiter,
    TokenBucketRateLimiter,
)
from .broker_client import BrokerClient
from .conversation import ConversationPublisher, PreparedConversation, ReplyResult
from .errors import (
    BrokerPolicyError,
    BrokerRateLimitError,
    BrokerRejectionError,
    GitHubAuthConfigurationError,
    GitHubAuthError,
    GitHubAuthInsufficientPermissionError,
    GitHubAuthTransientError,
    GitHubAuthUnavailableInstallationError,
    GitHubBrokerClientError,
    GitHubConversationError,
    GitHubConversationTransientError,
    GitHubHTTPError,
    GitHubHTTPTransientError,
    GitHubLearningProposalError,
    GitHubLearningProposalTransientError,
    GitHubOIDCAudienceError,
    GitHubOIDCClaimsError,
    GitHubOIDCError,
    GitHubOIDCExpiredError,
    GitHubOIDCInvalidTokenError,
    GitHubOIDCIssuerError,
    GitHubOIDCSignatureError,
    GitHubPublicationError,
    GitHubPublicationTransientError,
    GitHubSetupError,
    GitHubSetupTransientError,
    GitHubWebhookError,
    GitHubWebhookSignatureError,
)
from .http import GitHubHttp
from .jwt import JWTAlgorithms, decode_jwt_parts, jwt_encode_rs256
from .learning_pr import LearningPRPublisher, LearningPRResult
from .oidc import (
    DEFAULT_OIDC_ISSUER,
    HttpJwksFetcher,
    JwksFetcher,
    VerifiedOIDCClaims,
    verify_oidc_token,
)
from .publication import PublicationResult, ReviewPublisher
from .setup import (
    GitHubSetupClient,
    GitHubSetupTransport,
    SetupFile,
    SetupPlan,
    SetupPlanBuilder,
    SetupPullRequestResult,
    SetupPullRequestService,
)
from .webhooks import (
    DeliveryLedger,
    EnvWebhookSecretSource,
    InMemoryDeliveryLedger,
    VerifiedDelivery,
    WebhookSecretSource,
    WebhookVerifier,
)

__all__ = [
    "AppInstallationToken",
    "ApprovedWorkflow",
    "AuditRecord",
    "AuditSink",
    "BrokerClient",
    "BrokerPolicy",
    "BrokerPolicyError",
    "BrokerRateLimitError",
    "BrokerRejectionError",
    "ConversationPublisher",
    "PreparedConversation",
    "DEFAULT_BROKER_AUDIENCE",
    "DEFAULT_OIDC_ISSUER",
    "EnvPrivateKeySource",
    "FilePrivateKeySource",
    "ForkChecker",
    "GitHubApplication",
    "GitHubAppAuth",
    "GitHubBrokerClientError",
    "GitHubAuthConfigurationError",
    "GitHubAuthError",
    "GitHubAuthInsufficientPermissionError",
    "GitHubAuthTransientError",
    "GitHubAuthUnavailableInstallationError",
    "GitHubConversationError",
    "GitHubConversationTransientError",
    "GitHubForkChecker",
    "GitHubHTTPError",
    "GitHubHTTPTransientError",
    "GitHubHttp",
    "GitHubInstallationLookup",
    "GitHubLearningProposalError",
    "GitHubLearningProposalTransientError",
    "GitHubOIDCAudienceError",
    "GitHubOIDCClaimsError",
    "GitHubOIDCError",
    "GitHubOIDCExpiredError",
    "GitHubOIDCInvalidTokenError",
    "GitHubOIDCIssuerError",
    "GitHubOIDCSignatureError",
    "GitHubPublicationError",
    "GitHubPublicationTransientError",
    "GitHubSetupClient",
    "GitHubSetupError",
    "GitHubSetupTransientError",
    "GitHubSetupTransport",
    "GitHubTokenTransport",
    "InstallationToken",
    "InstallationTokenScope",
    "InstallationMapping",
    "InMemoryAuditSink",
    "InMemoryInstallationMapping",
    "DeliveryLedger",
    "EnvWebhookSecretSource",
    "InMemoryDeliveryLedger",
    "JWTAlgorithms",
    "LearningPRPublisher",
    "LearningPRResult",
    "PrivateKeySource",
    "PublicationResult",
    "RequestedPermissions",
    "ReplyResult",
    "ReviewPublisher",
    "GitHubWriteOptions",
    "HttpJwksFetcher",
    "JwksFetcher",
    "OIDCBroker",
    "RateLimiter",
    "SetupFile",
    "SetupPlan",
    "SetupPlanBuilder",
    "SetupPullRequestResult",
    "SetupPullRequestService",
    "TokenBucketRateLimiter",
    "VerifiedDelivery",
    "VerifiedOIDCClaims",
    "WebhookSecretSource",
    "WebhookVerifier",
    "decode_jwt_parts",
    "jwt_encode_rs256",
    "verify_oidc_token",
    "GitHubWebhookError",
    "GitHubWebhookSignatureError",
]
