#!/usr/bin/env python3
"""Commit a verified release docs snapshot to fresh main without bypassing rules."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import release_docs as docs

SNAPSHOT = "docs/releases/latest"
INDEX = "docs/releases/latest.md"
MAX_ATTEMPTS = 3


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(root), *args], text=True, stderr=subprocess.PIPE
    ).strip()


def index_text(selection: dict[str, Any]) -> str:
    prefix = f"https://github.com/{docs.REPOSITORY}"
    tag, sha, version = (
        selection["tag"],
        selection["source_sha"],
        selection["version"],
    )
    return (
        "<!-- Generated by sync_release_docs.py; do not edit. -->\n\n"
        f"# Released documentation: {tag}\n\n"
        f"This snapshot describes [{tag}]({prefix}/releases/tag/{tag}) from "
        f"verified source [{sha}]({prefix}/tree/{sha}).\n\n"
        "- [Static site snapshot](latest/site/index.html)\n"
        "- [Build provenance](latest/site/data/release-provenance.json)\n"
        f"- [Source documentation]({prefix}/tree/{sha}/docs)\n"
        f"- [Source examples]({prefix}/tree/{sha}/examples)\n\n"
        "```bash\n"
        f"pip install review-sensei=={version}\n"
        f"npx @reviewsensei/cli@{version} --help\n"
        "```\n\n"
        "The workflow channel remains `@v5`. Current source documentation on "
        "main may describe later development; this generated snapshot remains "
        "bound to the release source above.\n"
    )


def stored_selection(snapshot: Path) -> dict[str, Any]:
    provenance = json.loads(
        (snapshot / "site/data/release-provenance.json").read_text(encoding="utf-8")
    )
    result = {
        key: provenance[key]
        for key in (
            "schema_version",
            "repository",
            "tag",
            "version",
            "source_sha",
            "tag_object_sha",
            "release_run_id",
        )
    }
    docs.version_tuple(result["tag"])
    if (
        result["repository"] != docs.REPOSITORY
        or result["schema_version"] != "1.0"
        or result["version"] != result["tag"][1:]
        or not docs.SHA.fullmatch(result["source_sha"])
        or not docs.SHA.fullmatch(result["tag_object_sha"])
    ):
        raise ValueError("stored released docs identity is invalid")
    result["release_run_attempt"] = provenance["build_run_attempt"]
    docs.verify_bundle(snapshot, result)
    return result


def safe_paths(root: Path) -> None:
    # Never follow a tracked symlink into source, workflows or outside the clone.
    for relative in ("docs", "docs/releases", SNAPSHOT, INDEX):
        if (root / relative).is_symlink():
            raise ValueError(f"generated docs path is a symlink: {relative}")


def prepare(root: Path, bundle: Path, selection: dict[str, Any]) -> bool:
    """Replace only the generated snapshot; same immutable cutoff is a no-op."""
    safe_paths(root)
    docs.verify_bundle(bundle, selection)
    snapshot, index = root / SNAPSHOT, root / INDEX
    if snapshot.exists() != index.exists():
        raise ValueError("stored generated docs snapshot/index is incomplete")
    if snapshot.exists():
        previous = stored_selection(snapshot)
        if index.read_text(encoding="utf-8") != index_text(previous):
            raise ValueError("stored generated docs index was modified")
        old_version = docs.version_tuple(previous["tag"])
        version = docs.version_tuple(selection["tag"])
        if old_version > version:
            raise ValueError("main already records a newer released docs cutoff")
        if old_version == version:
            if any(
                previous[key] != selection[key]
                for key in ("tag", "version", "source_sha", "tag_object_sha")
            ):
                raise ValueError("immutable released docs source identity changed")
            original_files = docs.file_inventory(snapshot / "site")
            incoming_files = docs.file_inventory(bundle / "site")
            original_provenance = json.loads(
                (snapshot / "site/data/release-provenance.json").read_text(
                    encoding="utf-8"
                )
            )
            incoming_provenance = json.loads(
                (bundle / "site/data/release-provenance.json").read_text(
                    encoding="utf-8"
                )
            )
            for files in (original_files, incoming_files):
                files.pop("data/release-provenance.json")
            for provenance in (original_provenance, incoming_provenance):
                provenance.pop("build_run_attempt")
                provenance.pop("release_run_id")
            if (
                original_files != incoming_files
                or original_provenance != incoming_provenance
            ):
                raise ValueError(
                    "same-tag generated docs differ from the verified artifact"
                )
            # Publisher/build retries may have different attempts/artifact IDs.
            # Preserve the first verified snapshot for this immutable cutoff.
            return False
        shutil.rmtree(snapshot)
    snapshot.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(bundle, snapshot)
    index.write_text(index_text(selection), encoding="utf-8")
    stored_selection(snapshot)
    return True


def validate_staged_paths(root: Path) -> None:
    changed = git(root, "diff", "--cached", "--name-only", "-z").split("\0")
    if any(
        path and path != INDEX and not path.startswith(SNAPSHOT + "/")
        for path in changed
    ):
        raise ValueError("docs writeback attempted a non-generated source change")
    git(root, "diff", "--cached", "--check")


def recheck(selection: dict[str, Any]) -> None:
    if docs.qualify(selection["release_run_id"]) != selection:
        raise ValueError("release identity changed; retry from the successful Release")
    docs.assert_latest(selection)


def check_main_rules() -> None:
    rules = docs.api("rules/branches/main")
    if any(rule.get("type") == "pull_request" for rule in rules):
        raise ValueError(
            "main requires a pull request: direct docs writeback is blocked by "
            "repository protection. No bypass, token or settings change is attempted"
        )


def sync(root: Path, bundle: Path, selection: dict[str, Any]) -> bool:
    """Integrate with fresh main, retrying only a verified branch advance."""
    docs.verify_bundle(bundle, selection)
    recheck(selection)
    # Read active rules, including rulesets (classic protection alone is not
    # sufficient). Even an actor with a bypass grant must obey this contract.
    check_main_rules()
    with tempfile.TemporaryDirectory(prefix="release-docs-main-") as temporary:
        checkout = Path(temporary) / "main"
        for attempt in range(MAX_ATTEMPTS):
            git(root, "fetch", "--no-tags", "origin", "refs/heads/main")
            base = git(root, "rev-parse", "FETCH_HEAD")
            git(root, "worktree", "add", "--detach", str(checkout), base)
            try:
                if git(checkout, "status", "--porcelain=v1", "--untracked-files=all"):
                    raise ValueError("main integration checkout must be clean")
                if not prepare(checkout, bundle, selection):
                    recheck(selection)
                    print(f"Main already records {selection['tag']}; no commit needed")
                    return False
                git(checkout, "add", "--", SNAPSHOT, INDEX)
                validate_staged_paths(checkout)
                git(
                    checkout,
                    "-c",
                    "user.name=github-actions[bot]",
                    "-c",
                    "user.email=41898282+github-actions[bot]@users.noreply.github.com",
                    "commit",
                    "-m",
                    f"docs: record released {selection['tag']}",
                )
                recheck(selection)
                check_main_rules()
                push = subprocess.run(
                    [
                        "git",
                        "-C",
                        str(checkout),
                        "-c",
                        "credential.helper=",
                        "-c",
                        "credential.helper=!gh auth git-credential",
                        "push",
                        "origin",
                        "HEAD:refs/heads/main",
                    ],
                    capture_output=True,
                    text=True,
                )
                if push.returncode == 0:
                    print(
                        f"Committed released documentation for {selection['tag']} to main"
                    )
                    return True
                # A policy/permission/network failure on an unchanged branch is
                # terminal. Never force-push or silently create a release PR.
                check_main_rules()
                git(root, "fetch", "--no-tags", "origin", "refs/heads/main")
                if git(root, "rev-parse", "FETCH_HEAD") == base:
                    raise ValueError(
                        "direct main docs push rejected; check repository rules and "
                        "GITHUB_TOKEN Contents write permission. No bypass attempted. "
                        + push.stderr.strip()
                    )
                if attempt + 1 == MAX_ATTEMPTS:
                    raise ValueError(
                        "main advanced during all three docs integration attempts"
                    )
            finally:
                git(root, "worktree", "remove", "--force", str(checkout))
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--bundle", type=Path, required=True)
    parser.add_argument("--selection-json", required=True)
    args = parser.parse_args()
    try:
        if not os.environ.get("GH_TOKEN"):
            raise ValueError(
                "GH_TOKEN is required for release qualification and docs writeback"
            )
        sync(
            args.root.resolve(), args.bundle.resolve(), json.loads(args.selection_json)
        )
    except (ValueError, OSError, KeyError, subprocess.CalledProcessError) as exc:
        print(f"release docs main update failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
